"""
Claude-powered child dialogue for Digi-Child.

Mira's spoken/acted responses are generated by the Claude API, grounded in the
developmental-psychology "library" below plus her live simulation state
(age, trust, volatility, temperament, consecutive mistreatments, setting).

This module is the "live" brain. If the Claude API is unavailable for any
reason -- no API key, the `anthropic` package isn't installed, a network or
API error -- callers (main.py) fall back to the rule-based engine in
`local_ai.py`. That fallback is the app's DEMO MODE: it always works offline,
so a live demo never breaks even without credentials.
"""

import os
import json

# ---------------------------------------------------------------------------
# .env loading (nothing else in the backend loads it, so do it here, safely)
# ---------------------------------------------------------------------------
def _load_env():
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if not os.path.exists(env_path):
        return
    try:
        with open(env_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, val = line.split("=", 1)
                # don't clobber a real environment variable
                os.environ.setdefault(key.strip(), val.strip())
    except OSError:
        pass


_load_env()

MODEL = os.environ.get("DIGICHILD_CLAUDE_MODEL", "claude-opus-4-8")

# Toggle: "claude" (force live), "local" (force demo), "auto" (default: try
# Claude, fall back to demo). Set DIGICHILD_AI=local to force demo mode.
AI_MODE = os.environ.get("DIGICHILD_AI", "auto").lower()

_client = None
_client_error = None


def available():
    """True if the Claude path should even be attempted."""
    if AI_MODE == "local":
        return False
    return bool(os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN"))


def _get_client():
    """Lazily build the Anthropic client; cache the failure so we don't retry construction every call."""
    global _client, _client_error
    if _client is not None:
        return _client
    if _client_error is not None:
        raise _client_error
    try:
        import anthropic  # noqa: F401
        _client = anthropic.Anthropic()  # resolves ANTHROPIC_API_KEY / auth token / ant profile
        return _client
    except Exception as exc:  # ImportError, missing creds, etc.
        _client_error = exc
        raise


# ---------------------------------------------------------------------------
# The developmental "library" Mira reasons from (the books in her memory)
# ---------------------------------------------------------------------------
LIBRARY = """You ground every reaction in these developmental-psychology sources:
- Ross W. Greene, "The Explosive Child": kids do well if they can; challenging behavior is a lagging skill / an unsolved problem, not manipulation. Under stress a low-trust, high-volatility child escalates rather than complies (a "Plan A" failure).
- Daniel J. Siegel & Tina Payne Bryson, "The Whole-Brain Child" and "Parenting from the Inside Out": name-it-to-tame-it; connect before you redirect; when a child is emotionally flooded the "upstairs brain" goes offline and reasoning shuts down.
- Adele Faber & Elaine Mazlish, "How to Talk So Kids Will Listen & Listen So Kids Will Talk": acknowledging feelings and offering real choices earns cooperation; commands and labels provoke resistance.
- John Bowlby & Mary Ainsworth, Attachment Theory: secure vs. anxious/avoidant patterns. Low trust produces hesitancy, testing, or withdrawal even when the parent is being warm.
- Chip Wood, "Yardsticks: Child and Adolescent Development": age-typical language, needs, attention span, and milestones for each stage."""

# JSON schema for the structured response (guarantees a parseable shape).
SCHEMA = {
    "type": "object",
    "properties": {
        "childLine": {
            "type": "string",
            "description": "What Mira says or does, in first person, 1-2 short age-appropriate sentences. A brief physical action may be included in *asterisks* (e.g. '*hides behind the couch*').",
        },
        "mood": {
            "type": "string",
            "enum": ["happy", "curious", "playful", "analytical", "guarded", "resistant", "withdrawn", "upset"],
        },
        "reasoning": {
            "type": "string",
            "description": "One clinical sentence explaining the developmental mechanism behind this reaction.",
        },
        "framework_cited": {
            "type": "string",
            "description": "The single book/framework most responsible, e.g. 'The Explosive Child (Ross Greene)'.",
        },
    },
    "required": ["childLine", "mood", "reasoning", "framework_cited"],
    "additionalProperties": False,
}


def generate_child_response(state, req, treatment, history, persona=""):
    """
    Generate Mira's reaction via Claude. Returns the same dict shape as
    local_ai.generate_child_response, plus 'mood' and 'source'.
    Raises on any failure so the caller can fall back to demo mode.
    """
    client = _get_client()

    age = getattr(req, "year", state.get("child_age", 5))
    band = getattr(req, "ageBand", "")
    location = getattr(req, "location", "home")
    message = getattr(req, "message", "")
    trust = state.get("trust", 50)
    security = state.get("security", 50)
    volatility = state.get("volatility", 50)
    curiosity = state.get("curiosity", 50)
    autonomy = state.get("autonomy", 50)
    temperament = state.get("temperament", "neutral")
    profile = state.get("temperament_profile", "cooperative")
    mistreatments = state.get("consecutive_mistreatments", 0)

    system = (
        "You role-play Mira, a digital child inside a clinical parenting simulator used for "
        "court-ordered and therapeutic de-escalation practice. You ARE Mira and never break "
        "character, never speak as an AI assistant, and never give parenting advice in her voice. "
        "Mira is emotionally real and unpredictable -- she is NOT agreeable by default. How she "
        "reacts depends on how she has been treated over time, her trust, and her volatility.\n\n"
        + LIBRARY
        + "\n\nSafety: keep all friction age-appropriate and representative of ordinary developmental "
        "challenges (defiance, sulking, testing limits, tears) -- never severe trauma or unsafe content. "
        "Put clinical explanation only in the 'reasoning' field, never in Mira's spoken line."
    )
    if persona:
        system += "\n\nStage persona: " + persona

    # recent transcript (works with either DB key naming)
    hist_lines = []
    for h in (history or []):
        parent = h.get("parent") or h.get("input") or ""
        mira = h.get("mira") or h.get("child") or ""
        if parent or mira:
            hist_lines.append(f"Parent: {parent}\nMira: {mira}")
    hist_block = "\n".join(hist_lines[-6:]) or "(no earlier exchange this session)"

    user = f"""Mira's current developmental state:
- Age: {age} years ({band})
- Trust: {trust}/100 | Security: {security}/100 | Volatility: {volatility}/100 | Curiosity: {curiosity}/100 | Autonomy: {autonomy}/100
- Temperament: {temperament} | clinical profile: {profile}
- Consecutive mistreatments: {mistreatments}
- Setting: {location}
- System read of the parent's latest input: {treatment}

Recent exchange:
{hist_block}

The parent just said (or did) to Mira: "{message}"

Respond as Mira reacting in this moment, consistent with her age, state, and the frameworks above."""

    resp = client.messages.create(
        model=MODEL,
        max_tokens=600,
        thinking={"type": "disabled"},  # short, real-time turns; keep latency low
        system=system,
        messages=[{"role": "user", "content": user}],
        output_config={"format": {"type": "json_schema", "schema": SCHEMA}},
    )

    text = next((b.text for b in resp.content if getattr(b, "type", None) == "text"), "")
    data = json.loads(text)
    return {
        "childLine": data["childLine"],
        "reasoning": data.get("reasoning", ""),
        "framework_cited": data.get("framework_cited", ""),
        "mood": data.get("mood", ""),
        "source": "claude",
    }


# ---------------------------------------------------------------------------
# Agent 1 tool: parse chaotic parent availability text into ISO windows
# ---------------------------------------------------------------------------
_AVAIL_SCHEMA = {
    "type": "object",
    "properties": {
        "windows": {
            "type": "array",
            "description": "Concrete availability windows the parent gave, as ISO 8601 datetimes.",
            "items": {
                "type": "object",
                "properties": {
                    "start": {"type": "string", "description": "ISO 8601 start, e.g. 2026-07-14T09:00:00"},
                    "end": {"type": "string", "description": "ISO 8601 end"},
                    "label": {"type": "string", "description": "Short human label, e.g. 'Tue 9am-12pm'"},
                },
                "required": ["start", "end", "label"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["windows"],
    "additionalProperties": False,
}


def parse_availability(raw_text, now_iso):
    """
    Agent 1's Claude-backed availability parser: chaotic free text -> ISO windows.
    Returns a list of {start, end, label}. Raises on any failure so the caller
    can fall back to the regex parser (demo mode).
    """
    client = _get_client()
    system = (
        "You convert a parent's free-text availability into concrete ISO 8601 datetime windows "
        "for scheduling a clinical evaluation. Rules:\n"
        f"- The current datetime is {now_iso}. Resolve every relative reference against it "
        "('tomorrow', 'next Tuesday', 'this weekend').\n"
        "- Only return windows in the future.\n"
        "- Named parts of day (unless the parent gives explicit times): morning = 09:00-12:00, "
        "afternoon = 12:00-17:00, evening = 17:00-20:00.\n"
        "- 'after 9am' with no end -> 09:00-12:00; 'between 1 and 3pm' -> 13:00-15:00.\n"
        "- Local time, no timezone offset in the output."
    )
    resp = client.messages.create(
        model=MODEL,
        max_tokens=700,
        thinking={"type": "disabled"},
        system=system,
        messages=[{"role": "user", "content": f'Parent availability message:\n"{raw_text}"'}],
        output_config={"format": {"type": "json_schema", "schema": _AVAIL_SCHEMA}},
    )
    text = next((b.text for b in resp.content if getattr(b, "type", None) == "text"), "")
    data = json.loads(text)
    return data.get("windows", [])
