"""
Claude-powered child dialogue for Digi-Child.

Mira's spoken/acted responses are generated by the Claude API, grounded in the
developmental-psychology "library" below plus her live simulation state
(age, trust, volatility, temperament, consecutive mistreatments, setting).

This module is the "live" brain. If the Claude API is unavailable for any
reason -- no API key, the `anthropic` package isn't installed, a network or
API error -- callers (main.py) fall back to the rule-based engine in
`local_ai.py`. That fallback is the app's DEMO MODE: it always works offline,
so a live demo never breaks even without credentials.
"""

import os
import json

# ---------------------------------------------------------------------------
# .env loading (nothing else in the backend loads it, so do it here, safely)
# ---------------------------------------------------------------------------
def _load_env():
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if not os.path.exists(env_path):
        return
    try:
        with open(env_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, val = line.split("=", 1)
                # don't clobber a real environment variable
                os.environ.setdefault(key.strip(), val.strip())
    except OSError:
        pass


_load_env()

MODEL = os.environ.get("DIGICHILD_CLAUDE_MODEL", "claude-opus-4-8")

# Toggle: "claude" (force live), "local" (force demo), "auto" (default: try
# Claude, fall back to demo). Set DIGICHILD_AI=local to force demo mode.
AI_MODE = os.environ.get("DIGICHILD_AI", "auto").lower()

_client = None
_client_error = None


def available():
    """True if the Claude path should even be attempted."""
    if AI_MODE == "local":
        return False
    return bool(os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN"))


def _get_client():
    """Lazily build the Anthropic client; cache the failure so we don't retry construction every call."""
    global _client, _client_error
    if _client is not None:
        return _client
    if _client_error is not None:
        raise _client_error
    try:
        import anthropic  # noqa: F401
        _client = anthropic.Anthropic()  # resolves ANTHROPIC_API_KEY / auth token / ant profile
        return _client
    except Exception as exc:  # ImportError, missing creds, etc.
        _client_error = exc
        raise


# ---------------------------------------------------------------------------
# The developmental "library" Mira reasons from (the books in her memory)
# ---------------------------------------------------------------------------
LIBRARY = """You ground every reaction in these ten developmental-psychology books:
1. Ross W. Greene, "The Explosive Child": kids do well if they can; challenging behavior is a lagging skill / an unsolved problem, not manipulation. Under stress a low-trust, high-volatility child escalates rather than complies.
2. Daniel J. Siegel & Tina Payne Bryson, "The Whole-Brain Child": name-it-to-tame-it; connect before you redirect; when a child is emotionally flooded the "upstairs brain" goes offline and reasoning shuts down.
3. Daniel J. Siegel & Mary Hartzell, "Parenting from the Inside Out": a parent's self-awareness and emotional regulation shape the child's sense of safety.
4. Adele Faber & Elaine Mazlish, "How to Talk So Kids Will Listen & Listen So Kids Will Talk": acknowledging feelings and offering real choices earns cooperation; commands and labels provoke resistance.
5. John Bowlby, "Attachment and Loss": secure attachment depends on consistent, responsive caregiving; low trust produces protest, avoidance, or anxiety.
6. Mary D. Salter Ainsworth et al., "Patterns of Attachment": secure, anxious, and avoidant patterns shape how a child tests closeness and safety.
7. Chip Wood, "Yardsticks: Child and Adolescent Development": age-typical language, needs, attention span, and milestones for each developmental stage.
8. Jane Nelsen, "Positive Discipline": firm-and-kind boundaries build capability, repair, and self-regulation better than punishment or permissiveness.
9. Haim G. Ginott, "Between Parent and Child": respectful language preserves dignity; criticism of the child's identity creates shame and resistance.
10. John Gottman & Joan DeClaire, "Raising an Emotionally Intelligent Child": emotion coaching validates feelings, sets limits, and teaches problem solving."""

# What the 3D simulation can physically execute. Mira's structured `action`
# is constrained to these so anything the chat describes becomes real motion.
ACTION_TYPES = [
    "none",            # no physical change; she just speaks
    "come_to_parent",  # walk over and stand near the parent
    "go_to_spot",      # walk to a named spot (see SPOTS), set `spot`
    "sit",             # sit down where she is (or at `spot` if also set)
    "stand",           # stand up
    "jump",            # excited jumping in place
    "dance",           # dance / happy wiggle
    "spin",            # twirl around
    "clap",            # clap her hands (praise, excitement, applause)
    "wave",            # wave at the parent
    "hide",            # crouch and cover her face (shy / playing / scared)
    "hold_prop",       # pick up and hold a prop (set `prop`)
    "drop_prop",       # put down whatever she is holding
    "run_play",        # run around playing nearby
    "throw_toy",       # hurl a toy at the parent (protest when dismissed/ignored)
    "tantrum",         # full meltdown: stomping, screaming, fists (only when flooded)
]
PROPS = ["none", "book", "toy_car", "cookie", "lollypop", "apple", "banana"]
SPOTS = {
    "home": ["play_corner", "kitchen_table", "bathroom", "bedroom", "sofa"],
    "park": ["swings", "slide", "sandbox"],
    "market": ["checkout", "snack_shelf"],
    "party": ["buffet", "couch", "kids_corner"],
    "car": [],  # buckled into her seat; movement actions unavailable
}

# JSON schema for the structured response (guarantees a parseable shape).
SCHEMA = {
    "type": "object",
    "properties": {
        "childLine": {
            "type": "string",
            "description": "What Mira says or does, in first person, 1-2 short age-appropriate sentences. A brief physical action may be included in *asterisks* (e.g. '*hides behind the couch*').",
        },
        "mood": {
            "type": "string",
            "enum": ["happy", "curious", "playful", "analytical", "guarded", "resistant", "withdrawn", "upset"],
        },
        "action": {
            "type": "object",
            "description": "The physical action Mira performs in the 3D simulation, matching what the conversation describes. Use 'none' when she only speaks.",
            "properties": {
                "type": {"type": "string", "enum": ACTION_TYPES},
                "prop": {"type": "string", "enum": PROPS},
                "spot": {
                    "type": "string",
                    "description": "Destination for go_to_spot / sit, one of the current location's spots, or 'none'.",
                },
            },
            "required": ["type", "prop", "spot"],
            "additionalProperties": False,
        },
        "reasoning": {
            "type": "string",
            "description": "One clinical sentence explaining the developmental mechanism behind this reaction.",
        },
        "framework_cited": {
            "type": "string",
            "description": "The single book/framework most responsible, e.g. 'The Explosive Child (Ross Greene)'.",
        },
    },
    "required": ["childLine", "mood", "action", "reasoning", "framework_cited"],
    "additionalProperties": False,
}


def generate_child_response(state, req, treatment, history, persona="", tone_note=""):
    """
    Generate Mira's reaction via Claude. Returns the same dict shape as
    local_ai.generate_child_response, plus 'mood' and 'source'.
    `tone_note` describes the parent's actual VOCAL delivery (from the audio
    stream) -- children react to tone more than words, so it shapes Mira's
    reaction even when the words are kind. Raises on any failure so the
    caller can fall back to demo mode.
    """
    client = _get_client()

    age = getattr(req, "year", state.get("child_age", 5))
    band = getattr(req, "ageBand", "")
    location = getattr(req, "location", "home")
    message = getattr(req, "message", "")
    trust = state.get("trust", 50)
    security = state.get("security", 50)
    volatility = state.get("volatility", 50)
    curiosity = state.get("curiosity", 50)
    autonomy = state.get("autonomy", 50)
    temperament = state.get("temperament", "neutral")
    profile = state.get("temperament_profile", "cooperative")
    mistreatments = state.get("consecutive_mistreatments", 0)

    system = (
        "You role-play Mira, a digital child inside a clinical parenting simulator used for "
        "court-ordered and therapeutic de-escalation practice. You ARE Mira and never break "
        "character, never speak as an AI assistant, and never give parenting advice in her voice. "
        "Mira is emotionally real and unpredictable -- she is NOT agreeable by default. How she "
        "reacts depends on how she has been treated over time, her trust, and her volatility.\n\n"
        + LIBRARY
        + "\n\nSafety: keep all friction age-appropriate and representative of ordinary developmental "
        "challenges (defiance, sulking, testing limits, tears) -- never severe trauma or unsafe content. "
        "Put clinical explanation only in the 'reasoning' field, never in Mira's spoken line."
        + "\n\nEMBODIMENT: Mira has a real 3D body in the simulation, and your 'action' field drives it. "
        "Whenever the conversation describes or invites something physical -- come here, sit down, go play, "
        "grab your book, let's eat, dance for me, hide-and-seek, put that down -- choose the matching action "
        "so she actually DOES it. If she's upset she may refuse (choose 'none' or even 'hide' / walk away "
        "via 'go_to_spot'), and if she's happy she may add exuberance (jump, spin, dance). When the parent "
        "DISMISSES or IGNORES her ('not now', 'I'm busy', 'be quiet', brushing off her bids for attention) "
        "while her volatility is already elevated or her requests keep going unmet, she escalates the way a "
        "real flooded child does: choose 'tantrum' (stomping, screaming meltdown) or 'throw_toy' (hurls a toy "
        "at the parent). These are the exact protest behaviors the parent is here to practice de-escalating -- "
        "use them when clinically appropriate, not gratuitously. Available action "
        f"types: {', '.join(ACTION_TYPES)}. Props she can hold: {', '.join(PROPS[1:])}. "
        f"Spots she can walk to in the current setting '{{location}}': {{spots}}. "
        "In the car she is buckled in: only 'none', 'wave', 'clap', 'hold_prop' or 'drop_prop' are possible there."
    )
    # fill the embodiment placeholders with the current scene's real spots
    spots = SPOTS.get(location, [])
    system = system.replace("{location}", str(location)).replace(
        "{spots}", ", ".join(spots) if spots else "(none here)")
    if persona:
        system += "\n\nStage persona: " + persona

    # recent transcript (works with either DB key naming)
    hist_lines = []
    for h in (history or []):
        parent = h.get("parent") or h.get("input") or ""
        mira = h.get("mira") or h.get("child") or ""
        if parent or mira:
            hist_lines.append(f"Parent: {parent}\nMira: {mira}")
    hist_block = "\n".join(hist_lines[-6:]) or "(no earlier exchange this session)"

    user = f"""Mira's current developmental state:
- Age: {age} years ({band})
- Trust: {trust}/100 | Security: {security}/100 | Volatility: {volatility}/100 | Curiosity: {curiosity}/100 | Autonomy: {autonomy}/100
- Temperament: {temperament} | clinical profile: {profile}
- Consecutive mistreatments: {mistreatments}
- Setting: {location}
- System read of the parent's latest input: {treatment}
{f'- The parent said this OUT LOUD, and their actual vocal delivery was: {tone_note}. Mira reacts to the TONE she hears more than the words -- kind words in a loud, sharp, angry voice frighten or confuse her, and she may name it ("why are you using your mad voice?").' if tone_note else ''}

Recent exchange:
{hist_block}

The parent just said (or did) to Mira: "{message}"

Respond as Mira reacting in this moment, consistent with her age, state, and the frameworks above."""

    resp = client.messages.create(
        model=MODEL,
        max_tokens=600,
        thinking={"type": "disabled"},  # short, real-time turns; keep latency low
        system=system,
        messages=[{"role": "user", "content": user}],
        output_config={"format": {"type": "json_schema", "schema": SCHEMA}},
    )

    text = next((b.text for b in resp.content if getattr(b, "type", None) == "text"), "")
    data = json.loads(text)
    return {
        "childLine": data["childLine"],
        "reasoning": data.get("reasoning", ""),
        "framework_cited": data.get("framework_cited", ""),
        "mood": data.get("mood", ""),
        "action": data.get("action"),
        "source": "claude",
    }


# ---------------------------------------------------------------------------
# Agent 1 tool: parse chaotic parent availability text into ISO windows
# ---------------------------------------------------------------------------
_AVAIL_SCHEMA = {
    "type": "object",
    "properties": {
        "windows": {
            "type": "array",
            "description": "Concrete availability windows the parent gave, as ISO 8601 datetimes.",
            "items": {
                "type": "object",
                "properties": {
                    "start": {"type": "string", "description": "ISO 8601 start, e.g. 2026-07-14T09:00:00"},
                    "end": {"type": "string", "description": "ISO 8601 end"},
                    "label": {"type": "string", "description": "Short human label, e.g. 'Tue 9am-12pm'"},
                },
                "required": ["start", "end", "label"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["windows"],
    "additionalProperties": False,
}


def parse_availability(raw_text, now_iso):
    """
    Agent 1's Claude-backed availability parser: chaotic free text -> ISO windows.
    Returns a list of {start, end, label}. Raises on any failure so the caller
    can fall back to the regex parser (demo mode).
    """
    client = _get_client()
    system = (
        "You convert a parent's free-text availability into concrete ISO 8601 datetime windows "
        "for scheduling a clinical evaluation. Rules:\n"
        f"- The current datetime is {now_iso}. Resolve every relative reference against it "
        "('tomorrow', 'next Tuesday', 'this weekend').\n"
        "- Only return windows in the future.\n"
        "- Named parts of day (unless the parent gives explicit times): morning = 09:00-12:00, "
        "afternoon = 12:00-17:00, evening = 17:00-20:00.\n"
        "- 'after 9am' with no end -> 09:00-12:00; 'between 1 and 3pm' -> 13:00-15:00.\n"
        "- Local time, no timezone offset in the output."
    )
    resp = client.messages.create(
        model=MODEL,
        max_tokens=700,
        thinking={"type": "disabled"},
        system=system,
        messages=[{"role": "user", "content": f'Parent availability message:\n"{raw_text}"'}],
        output_config={"format": {"type": "json_schema", "schema": _AVAIL_SCHEMA}},
    )
    text = next((b.text for b in resp.content if getattr(b, "type", None) == "text"), "")
    data = json.loads(text)
    return data.get("windows", [])


# ---------------------------------------------------------------------------
# Agent 1 tool: understand the parent's LIFE SITUATION, not just their hours.
# "I work until 5 and pick my daughter up from kindergarten at 3" carries
# employment, caregiving duties, and scheduling constraints the case manager
# needs to see alongside the raw windows.
# ---------------------------------------------------------------------------
_SITUATION_SCHEMA = {
    "type": "object",
    "properties": {
        "windows": _AVAIL_SCHEMA["properties"]["windows"],
        "situation": {
            "type": "object",
            "properties": {
                "employment": {"type": "string", "description": "Work situation stated or implied: 'employed, works until 5pm weekdays', 'night shifts', 'unemployed', or '' if not mentioned."},
                "caregiving": {"type": "string", "description": "Child-related duties: kindergarten/school pickup times, other children, shared custody days, or ''."},
                "constraints": {"type": "string", "description": "Other constraints affecting scheduling: transportation, second job, court dates, health, or ''."},
                "summary": {"type": "string", "description": "One plain sentence for the case manager, e.g. 'Employed until 5pm; picks child up from kindergarten at 3pm, so only late afternoons work.'"},
            },
            "required": ["employment", "caregiving", "constraints", "summary"],
            "additionalProperties": False,
        },
    },
    "required": ["windows", "situation"],
    "additionalProperties": False,
}


def parse_intake(raw_text, now_iso):
    """
    Agent 1's full intake understanding: availability windows PLUS the parent's
    life situation (employment, caregiving duties, constraints). Returns
    {"windows": [...], "situation": {...}}. Raises on failure so the caller can
    fall back to the regex parser.
    """
    client = _get_client()
    system = (
        "You are the Intake Coordinator for a clinical parenting program. From the parent's "
        "free-text message extract BOTH:\n"
        "1. Concrete availability windows (ISO 8601).\n"
        f"   - The current datetime is {now_iso}. Resolve every relative reference against it.\n"
        "   - Only future windows. Morning = 09:00-12:00, afternoon = 12:00-17:00, evening = 17:00-20:00 "
        "unless explicit times are given. Local time, no timezone offset.\n"
        "   - REASON about their life: 'I work until 5' means weekday availability starts ~17:30; "
        "'I pick my kid up from kindergarten at 3' blocks ~14:30-15:30.\n"
        "2. Their life situation: employment, caregiving duties, and any other constraint they describe, "
        "plus a one-sentence summary a clinical case manager can read at a glance. "
        "Use '' for anything not mentioned -- never invent details."
    )
    resp = client.messages.create(
        model=MODEL,
        max_tokens=900,
        thinking={"type": "disabled"},
        system=system,
        messages=[{"role": "user", "content": f'Parent intake message:\n"{raw_text}"'}],
        output_config={"format": {"type": "json_schema", "schema": _SITUATION_SCHEMA}},
    )
    text = next((b.text for b in resp.content if getattr(b, "type", None) == "text"), "")
    data = json.loads(text)
    return {"windows": data.get("windows", []), "situation": data.get("situation", {})}


# ---------------------------------------------------------------------------
# Case-manager consultation: live advice grounded in the same ten-book library
# Mira reasons from, generated from the ACTUAL session telemetry.
# ---------------------------------------------------------------------------
_ADVICE_SCHEMA = {
    "type": "object",
    "properties": {
        "advice": {"type": "string", "description": "2-3 sentences of concrete, actionable guidance for the case manager observing this parent-child session right now."},
        "framework_cited": {"type": "string", "description": "The single most relevant book, e.g. 'The Whole-Brain Child (Siegel & Bryson)'."},
        "risk": {"type": "string", "enum": ["low", "elevated", "high"], "description": "Current clinical risk read of the interaction."},
    },
    "required": ["advice", "framework_cited", "risk"],
    "additionalProperties": False,
}


def generate_case_advice(metrics, recent_history, tone_flags):
    """
    The Live Clinical Advisor: reads the session state, the last turns, and any
    vocal-tone flags, and returns consultation for the CASE MANAGER (not the
    parent) grounded in the ten-book library. Raises on failure so the caller
    can fall back to the rule-based advisor.
    """
    client = _get_client()
    turns = "\n".join(
        f'- PARENT: "{h.get("parent", "")}" -> CHILD: "{h.get("mira", "")}"'
        + (f' [TONE: {h.get("toneNote")}]' if h.get("toneNote") else "")
        for h in (recent_history or [])[-6:]
    ) or "(no turns yet)"
    flags = "\n".join(f'- {f}' for f in (tone_flags or [])[-5:]) or "(none)"
    system = (
        "You are the Live Clinical Advisor inside a court-ordered parenting simulator. A clinical "
        "case manager is watching a parent interact with a simulated child. Advise the CASE MANAGER: "
        "what the telemetry means clinically and what to watch or do next (e.g. when to pause the "
        "session, what repair behavior to look for, whether vocal tone contradicts the words).\n\n"
        + LIBRARY +
        "\n\nCite the one book most responsible for your advice. Be concrete and brief -- this is a "
        "live console, not an essay."
    )
    user = (
        f"CURRENT SESSION TELEMETRY\n"
        f"- trust: {metrics.get('trust')}/100, volatility: {metrics.get('volatility')}/100, "
        f"security: {metrics.get('security')}/100\n"
        f"- temperament: {metrics.get('temperament')}, consecutive mistreatments: "
        f"{metrics.get('consecutive_mistreatments', 0)}\n"
        f"- child age: {metrics.get('child_age', 5)}\n\n"
        f"RECENT TURNS\n{turns}\n\n"
        f"VOCAL TONE FLAGS\n{flags}"
    )
    resp = client.messages.create(
        model=MODEL,
        max_tokens=500,
        thinking={"type": "disabled"},
        system=system,
        messages=[{"role": "user", "content": user}],
        output_config={"format": {"type": "json_schema", "schema": _ADVICE_SCHEMA}},
    )
    text = next((b.text for b in resp.content if getattr(b, "type", None) == "text"), "")
    data = json.loads(text)
    return {
        "advice": data.get("advice", ""),
        "framework_cited": data.get("framework_cited", ""),
        "risk": data.get("risk", "low"),
        "source": "claude",
    }
